default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: admin1234
  host: localhost
  port: 5432

development:
  <<: *default
  database: makey_platform_development

test:
  <<: *default
  database: makey_platform_test

production:
  <<: *default
  database: makey_platform_production
  username: makey_production
  password: <%= ENV['MAKEY_PLATFORM_DATABASE_PASSWORD'] %>

